from __future__ import annotations

from typing import Optional, Tuple

import torch

HAS_CUDA: bool
__version__: str


class Camera:
    azimuth: float
    elevation: float
    distance: float
    target: Tuple[float, float, float]
    fov: float

    def reset(self) -> None: ...


class Light:
    direction: Tuple[float, float, float]
    color: Tuple[float, float, float]
    intensity: float
    ambient: float
    specular: float
    shininess: float
    enabled: bool


class Window:
    _current: Optional["Window"]

    def __init__(self, title: str = "Vultorch", width: int = 1280, height: int = 720) -> None: ...
    def activate(self) -> None: ...
    def poll(self) -> bool: ...
    def begin_frame(self) -> bool: ...
    def end_frame(self) -> None: ...
    def upload_tensor(self, tensor: torch.Tensor, *, name: str = "tensor") -> None: ...

    @property
    def tensor_texture_id(self) -> int: ...
    def get_texture_id(self, name: str = "tensor") -> int: ...

    @property
    def tensor_size(self) -> Tuple[int, int]: ...
    def get_texture_size(self, name: str = "tensor") -> Tuple[int, int]: ...

    def destroy(self) -> None: ...


def show(
    tensor: torch.Tensor,
    *,
    name: str = "tensor",
    width: float = 0,
    height: float = 0,
    filter: str = "linear",
    window: Optional[Window] = None,
) -> None: ...


def create_tensor(
    height: int,
    width: int,
    channels: int = 4,
    device: str = "cuda:0",
    *,
    name: str = "tensor",
    window: Optional[Window] = None,
) -> torch.Tensor: ...


class SceneView:
    name: str
    camera: Camera
    light: Light
    background: Tuple[float, float, float]

    def __init__(self, name: str = "SceneView", width: int = 800, height: int = 600, msaa: int = 4) -> None: ...
    def set_tensor(self, tensor: torch.Tensor) -> None: ...
    def render(self) -> None: ...

    @property
    def msaa(self) -> int: ...
    @msaa.setter
    def msaa(self, value: int) -> None: ...


from . import ui as ui


# ── Declarative API ─────────────────────────────────────────────────

class Canvas:
    def bind(self, tensor: torch.Tensor) -> "Canvas": ...
    def alloc(self, height: int, width: int, channels: int = 4, device: str = "cuda:0") -> torch.Tensor: ...
    @property
    def filter(self) -> str: ...
    @filter.setter
    def filter(self, value: str) -> None: ...
    @property
    def fit(self) -> bool: ...
    @fit.setter
    def fit(self, value: bool) -> None: ...


class Panel:
    def canvas(self, name: str, *, filter: str = "linear", fit: bool = True) -> Canvas: ...
    def row(self) -> object: ...
    def text(self, text: str) -> None: ...
    def text_colored(self, r: float, g: float, b: float, a: float, text: str) -> None: ...
    def text_wrapped(self, text: str) -> None: ...
    def separator(self) -> None: ...
    def button(self, label: str) -> bool: ...
    def checkbox(self, label: str, *, default: bool = False) -> bool: ...
    def slider(self, label: str, min: float = 0.0, max: float = 1.0, *, default: Optional[float] = None) -> float: ...
    def slider_int(self, label: str, min: int = 0, max: int = 100, *, default: int = 0) -> int: ...
    def color_picker(self, label: str, *, default: Tuple[float, float, float] = ...) -> Tuple[float, float, float]: ...
    def combo(self, label: str, items: list, *, default: int = 0) -> int: ...
    def input_text(self, label: str, *, default: str = "", max_length: int = 256) -> str: ...
    def plot(self, values: object, *, label: str = "##plot", overlay: str = "", width: float = 0.0, height: float = 80.0) -> None: ...
    def progress(self, fraction: float, *, overlay: str = "") -> None: ...


class View:
    def __init__(self, title: str = "Vultorch", width: int = 1280, height: int = 720) -> None: ...
    def panel(self, name: str, *, side: Optional[str] = None, width: float = 0.0) -> Panel: ...
    def on_frame(self, fn: object) -> object: ...
    def run(self) -> None: ...
    def step(self) -> bool: ...
    def end_step(self) -> None: ...
    def close(self) -> None: ...

    @property
    def fps(self) -> float: ...
    @property
    def time(self) -> float: ...
    @property
    def window(self) -> Window: ...
