from __future__ import annotations

from typing import Sequence, Tuple


def begin(name: str, opened: bool = True, flags: int = 0) -> Tuple[bool, bool]: ...
def end() -> None: ...

def begin_child(id: str, width: float = 0.0, height: float = 0.0, child_flags: int = 0, window_flags: int = 0) -> bool: ...
def end_child() -> None: ...

def text(text: str) -> None: ...
def text_wrapped(text: str) -> None: ...
def text_colored(r: float, g: float, b: float, a: float, text: str) -> None: ...
def text_disabled(text: str) -> None: ...

def button(label: str, width: float = 0.0, height: float = 0.0) -> bool: ...
def small_button(label: str) -> bool: ...
def invisible_button(id: str, width: float, height: float) -> bool: ...

def checkbox(label: str, value: bool) -> bool: ...

def slider_float(label: str, value: float, min: float = 0.0, max: float = 1.0, format: str = "%.3f") -> float: ...
def slider_int(label: str, value: int, min: int = 0, max: int = 100) -> int: ...

def color_edit3(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, flags: int = 0) -> Tuple[float, float, float]: ...
def color_edit4(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 1.0, flags: int = 0) -> Tuple[float, float, float, float]: ...

def separator() -> None: ...

def image(texture_id: int, width: float, height: float, uv0x: float = 0.0, uv0y: float = 0.0, uv1x: float = 1.0, uv1y: float = 1.0) -> None: ...

def begin_group() -> None: ...
def end_group() -> None: ...

def get_content_region_avail() -> Tuple[float, float]: ...
def get_window_size() -> Tuple[float, float]: ...

def is_item_hovered() -> bool: ...

def get_mouse_pos() -> Tuple[float, float]: ...
def is_mouse_dragging(button: int = 0, lock_threshold: float = -1.0) -> bool: ...

def get_io_framerate() -> float: ...
def get_time() -> float: ...

# Docking

def dock_space_over_viewport(flags: int = 0) -> int: ...

def dock_builder_remove_node(node_id: int) -> None: ...
def dock_builder_add_node(node_id: int = 0, flags: int = 0) -> int: ...
def dock_builder_set_node_size(node_id: int, width: float, height: float) -> None: ...
def dock_builder_split_node(node_id: int, split_dir: int, size_ratio: float) -> Tuple[int, int]: ...
def dock_builder_dock_window(window_name: str, node_id: int) -> None: ...
def dock_builder_finish(node_id: int) -> None: ...

# Plot helpers

def plot_lines(label: str, values: Sequence[float], offset: int = 0, overlay: str = "", scale_min: float = ..., scale_max: float = ..., width: float = 0.0, height: float = 0.0) -> None: ...
def plot_histogram(label: str, values: Sequence[float], offset: int = 0, overlay: str = "", scale_min: float = ..., scale_max: float = ..., width: float = 0.0, height: float = 0.0) -> None: ...
