from __future__ import annotations

from typing import List, Sequence, Tuple


# ── Windows ─────────────────────────────────────────────────────────

def begin(name: str, opened: bool = True, flags: int = 0) -> Tuple[bool, bool]: ...
def end() -> None: ...

def begin_child(id: str, width: float = 0.0, height: float = 0.0, child_flags: int = 0, window_flags: int = 0) -> bool: ...
def end_child() -> None: ...

# ── Text / Labels ───────────────────────────────────────────────────

def text(text: str) -> None: ...
def text_wrapped(text: str) -> None: ...
def text_colored(r: float, g: float, b: float, a: float, text: str) -> None: ...
def text_disabled(text: str) -> None: ...
def label_text(label: str, text: str) -> None: ...
def bullet_text(text: str) -> None: ...

# ── Buttons ─────────────────────────────────────────────────────────

def button(label: str, width: float = 0.0, height: float = 0.0) -> bool: ...
def small_button(label: str) -> bool: ...
def invisible_button(id: str, width: float, height: float) -> bool: ...
def arrow_button(id: str, dir: int) -> bool: ...
def radio_button(label: str, active: bool) -> bool: ...

# ── Checkbox ────────────────────────────────────────────────────────

def checkbox(label: str, value: bool) -> bool: ...

# ── Sliders ─────────────────────────────────────────────────────────

def slider_float(label: str, value: float, min: float = 0.0, max: float = 1.0, format: str = "%.3f") -> float: ...
def slider_float2(label: str, v0: float, v1: float, min: float = 0.0, max: float = 1.0) -> Tuple[float, float]: ...
def slider_float3(label: str, v0: float, v1: float, v2: float, min: float = 0.0, max: float = 1.0) -> Tuple[float, float, float]: ...
def slider_float4(label: str, v0: float, v1: float, v2: float, v3: float, min: float = 0.0, max: float = 1.0) -> Tuple[float, float, float, float]: ...
def slider_int(label: str, value: int, min: int = 0, max: int = 100) -> int: ...
def slider_angle(label: str, value_rad: float, min_deg: float = -360.0, max_deg: float = 360.0) -> float: ...

# ── Drag Inputs ─────────────────────────────────────────────────────

def drag_float(label: str, value: float, speed: float = 1.0, min: float = 0.0, max: float = 0.0) -> float: ...
def drag_float2(label: str, v0: float, v1: float, speed: float = 1.0, min: float = 0.0, max: float = 0.0) -> Tuple[float, float]: ...
def drag_float3(label: str, v0: float, v1: float, v2: float, speed: float = 1.0, min: float = 0.0, max: float = 0.0) -> Tuple[float, float, float]: ...
def drag_int(label: str, value: int, speed: float = 1.0, min: int = 0, max: int = 0) -> int: ...

# ── Input Fields ────────────────────────────────────────────────────

def input_float(label: str, value: float, step: float = 0.0, step_fast: float = 0.0) -> float: ...
def input_float2(label: str, v0: float, v1: float) -> Tuple[float, float]: ...
def input_float3(label: str, v0: float, v1: float, v2: float) -> Tuple[float, float, float]: ...
def input_float4(label: str, v0: float, v1: float, v2: float, v3: float) -> Tuple[float, float, float, float]: ...
def input_int(label: str, value: int, step: int = 1, step_fast: int = 100) -> int: ...
def input_text(label: str, text: str = "", max_length: int = 256, flags: int = 0) -> str: ...
def input_text_multiline(label: str, text: str = "", max_length: int = 1024, width: float = 0.0, height: float = 0.0, flags: int = 0) -> str: ...

# ── Color ───────────────────────────────────────────────────────────

def color_edit3(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, flags: int = 0) -> Tuple[float, float, float]: ...
def color_edit4(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 1.0, flags: int = 0) -> Tuple[float, float, float, float]: ...
def color_picker3(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, flags: int = 0) -> Tuple[float, float, float]: ...
def color_picker4(label: str, r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 1.0, flags: int = 0) -> Tuple[float, float, float, float]: ...

# ── Combo / Listbox ─────────────────────────────────────────────────

def combo(label: str, current: int, items: List[str]) -> int: ...
def listbox(label: str, current: int, items: List[str], height_items: int = -1) -> int: ...

# ── Tree / Collapsing Headers ───────────────────────────────────────

def tree_node(label: str) -> bool: ...
def tree_pop() -> None: ...
def collapsing_header(label: str, flags: int = 0) -> bool: ...

# ── Selectable ──────────────────────────────────────────────────────

def selectable(label: str, selected: bool = False, flags: int = 0, width: float = 0.0, height: float = 0.0) -> bool: ...

# ── Tabs ────────────────────────────────────────────────────────────

def begin_tab_bar(id: str, flags: int = 0) -> bool: ...
def end_tab_bar() -> None: ...
def begin_tab_item(label: str) -> bool: ...
def end_tab_item() -> None: ...

# ── Progress Bar ────────────────────────────────────────────────────

def progress_bar(fraction: float, width: float = -1.0, height: float = 0.0, overlay: str = "") -> None: ...

# ── Image ───────────────────────────────────────────────────────────

def image(texture_id: int, width: float, height: float, uv0x: float = 0.0, uv0y: float = 0.0, uv1x: float = 1.0, uv1y: float = 1.0) -> None: ...
def image_button(id: str, texture_id: int, width: float, height: float) -> bool: ...

# ── Layout / Spacing ────────────────────────────────────────────────

def separator() -> None: ...
def same_line(offset: float = 0.0, spacing: float = -1.0) -> None: ...
def new_line() -> None: ...
def spacing() -> None: ...
def dummy(width: float, height: float) -> None: ...
def indent(width: float = 0.0) -> None: ...
def unindent(width: float = 0.0) -> None: ...
def begin_group() -> None: ...
def end_group() -> None: ...
def push_item_width(width: float) -> None: ...
def pop_item_width() -> None: ...

# ── Columns ─────────────────────────────────────────────────────────

def columns(count: int = 1, id: str = "", border: bool = True) -> None: ...
def next_column() -> None: ...

# ── Tables ──────────────────────────────────────────────────────────

def begin_table(id: str, columns: int, flags: int = 0, outer_width: float = 0.0, outer_height: float = 0.0, inner_width: float = 0.0) -> bool: ...
def end_table() -> None: ...
def table_next_row(flags: int = 0, min_row_height: float = 0.0) -> None: ...
def table_next_column() -> bool: ...
def table_set_column_index(index: int) -> bool: ...
def table_setup_column(label: str, flags: int = 0, init_width: float = 0.0) -> None: ...
def table_headers_row() -> None: ...

# ── Menu Bar ────────────────────────────────────────────────────────

def begin_main_menu_bar() -> bool: ...
def end_main_menu_bar() -> None: ...
def begin_menu_bar() -> bool: ...
def end_menu_bar() -> None: ...
def begin_menu(label: str, enabled: bool = True) -> bool: ...
def end_menu() -> None: ...
def menu_item(label: str, shortcut: str = "", selected: bool = False, enabled: bool = True) -> bool: ...

# ── Popups / Modals ─────────────────────────────────────────────────

def open_popup(id: str) -> None: ...
def begin_popup(id: str, flags: int = 0) -> bool: ...
def begin_popup_modal(name: str, flags: int = 0) -> bool: ...
def end_popup() -> None: ...
def close_current_popup() -> None: ...

# ── Tooltips ────────────────────────────────────────────────────────

def begin_tooltip() -> bool: ...
def end_tooltip() -> None: ...
def set_tooltip(text: str) -> None: ...

# ── ID Stack ────────────────────────────────────────────────────────

def push_id_str(id: str) -> None: ...
def push_id_int(id: int) -> None: ...
def pop_id() -> None: ...

# ── Style ───────────────────────────────────────────────────────────

def push_style_color(idx: int, r: float, g: float, b: float, a: float) -> None: ...
def pop_style_color(count: int = 1) -> None: ...
def push_style_var_float(idx: int, value: float) -> None: ...
def push_style_var_vec2(idx: int, x: float, y: float) -> None: ...
def pop_style_var(count: int = 1) -> None: ...
def style_colors_dark() -> None: ...
def style_colors_light() -> None: ...
def style_colors_classic() -> None: ...

# ── Cursor / Viewport ──────────────────────────────────────────────

def get_cursor_pos() -> Tuple[float, float]: ...
def set_cursor_pos(x: float, y: float) -> None: ...
def get_content_region_avail() -> Tuple[float, float]: ...
def get_window_size() -> Tuple[float, float]: ...
def get_window_pos() -> Tuple[float, float]: ...
def set_next_window_pos(x: float, y: float, cond: int = 0) -> None: ...
def set_next_window_size(width: float, height: float, cond: int = 0) -> None: ...

# ── Docking ─────────────────────────────────────────────────────────

def dock_space_over_viewport(flags: int = 0) -> int: ...
def dock_space(id: int, width: float = 0.0, height: float = 0.0, flags: int = 0) -> int: ...
def set_next_window_dock_id(dock_id: int, cond: int = 0) -> None: ...
def get_id(str_id: str) -> int: ...

def dock_builder_remove_node(node_id: int) -> None: ...
def dock_builder_add_node(node_id: int = 0, flags: int = 0) -> int: ...
def dock_builder_set_node_size(node_id: int, width: float, height: float) -> None: ...
def dock_builder_set_node_pos(node_id: int, x: float, y: float) -> None: ...
def dock_builder_split_node(node_id: int, split_dir: int, size_ratio: float) -> Tuple[int, int]: ...
def dock_builder_dock_window(window_name: str, node_id: int) -> None: ...
def dock_builder_finish(node_id: int) -> None: ...
def dock_builder_get_node(node_id: int) -> bool: ...

# ── Drawing (WindowDrawList) ────────────────────────────────────────

def draw_line(x1: float, y1: float, x2: float, y2: float, col: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
def draw_rect(x1: float, y1: float, x2: float, y2: float, col: int = 0xFFFFFFFF, rounding: float = 0.0, thickness: float = 1.0) -> None: ...
def draw_rect_filled(x1: float, y1: float, x2: float, y2: float, col: int = 0xFFFFFFFF, rounding: float = 0.0) -> None: ...
def draw_circle(cx: float, cy: float, radius: float, col: int = 0xFFFFFFFF, segments: int = 0, thickness: float = 1.0) -> None: ...
def draw_circle_filled(cx: float, cy: float, radius: float, col: int = 0xFFFFFFFF, segments: int = 0) -> None: ...
def draw_text(x: float, y: float, col: int, text: str) -> None: ...

# ── Background Draw List ────────────────────────────────────────────

def bg_draw_image(texture_id: int, x1: float, y1: float, x2: float, y2: float, uv0x: float = 0.0, uv0y: float = 0.0, uv1x: float = 1.0, uv1y: float = 1.0) -> None: ...
def get_display_size() -> Tuple[float, float]: ...

# ── Item State Queries ──────────────────────────────────────────────

def is_item_hovered() -> bool: ...
def is_item_active() -> bool: ...
def is_item_clicked(button: int = 0) -> bool: ...
def is_item_focused() -> bool: ...
def is_item_edited() -> bool: ...
def is_item_deactivated_after_edit() -> bool: ...

# ── Mouse State ─────────────────────────────────────────────────────

def get_mouse_pos() -> Tuple[float, float]: ...
def is_mouse_clicked(button: int = 0) -> bool: ...
def is_mouse_double_clicked(button: int = 0) -> bool: ...
def is_mouse_dragging(button: int = 0, lock_threshold: float = -1.0) -> bool: ...
def get_mouse_drag_delta(button: int = 0, lock_threshold: float = -1.0) -> Tuple[float, float]: ...

# ── Keyboard State ──────────────────────────────────────────────────

def is_key_pressed(key: int) -> bool: ...
def is_key_down(key: int) -> bool: ...

# ── Utility ─────────────────────────────────────────────────────────

def get_io_framerate() -> float: ...
def get_io_delta_time() -> float: ...
def get_time() -> float: ...
def get_frame_count() -> int: ...
def col32(r: int, g: int, b: int, a: int = 255) -> int: ...

# ── Plot Helpers ────────────────────────────────────────────────────

def plot_lines(label: str, values: Sequence[float], offset: int = 0, overlay: str = "", scale_min: float = ..., scale_max: float = ..., width: float = 0.0, height: float = 0.0) -> None: ...
def plot_histogram(label: str, values: Sequence[float], offset: int = 0, overlay: str = "", scale_min: float = ..., scale_max: float = ..., width: float = 0.0, height: float = 0.0) -> None: ...

# ── Demo / Debug ────────────────────────────────────────────────────

def show_demo_window() -> None: ...
def show_metrics_window() -> None: ...
